branch-defaults:
  default:
    environment: scottishhockeyreference-env
environment-defaults:
  scottishhockeyreference-env:
    branch: null
    repository: null
global:
  application_name: scottishhockeyreference
  default_ec2_keyname: null
  default_platform: .NET Core running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
